development:
  adapter: postgresql
  encoding: unicode
  database: vybes_development
  pool: 5
  username: williejohnson
  password: vybes_development

test:
  adapter: postgresql
  encoding: unicode
  database: vybes_test
  pool: 5
  username: williejohnson
  password: vybes_test


production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
